services:
  - type: web
    name: sevenz-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Sevenz.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
